In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os


In [2]:
os.getcwd()


'C:\\Users\\PC'

In [4]:
os.chdir('E:\\acmegrade')
os.getcwd()


'E:\\acmegrade'

In [6]:
df=pd.read_csv("audi.csv")
display(df)


model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [7]:
len(df)

10668

In [8]:
display (df.shape)

(10668, 9)

In [10]:
display (df.dtypes )
display (df.isna().sum() )


model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [11]:
df.info()
df.describe ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB


year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [13]:
x=df.iloc[:,[0,1,3,4,5,6,7,8]].values
display (x)


array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [25]:
y = df.iloc[:,[2]].values
display (y)



array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [26]:
display(pd.DataFrame(x).head(5))

0    1    2  3     4      5  6    7     8    9
0  0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1  1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2  0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3  1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4  0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0

In [27]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,0] = le1.fit_transform(x[:,0])
le2 = LabelEncoder()
x[:,-4] = le2.fit_transform(x[:,-4])
display (x)


array([[0, 1.0, 0.0, ..., 150, 55.4, 1.4],
       [1, 0.0, 0.0, ..., 20, 64.2, 2.0],
       [0, 1.0, 0.0, ..., 30, 55.4, 1.4],
       ...,
       [0, 1.0, 0.0, ..., 150, 49.6, 1.0],
       [1, 0.0, 0.0, ..., 150, 47.9, 1.4],
       [0, 1.0, 0.0, ..., 150, 47.9, 1.4]], dtype=object)

In [28]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x = ct.fit_transform(x)
display (pd.DataFrame(x))


0    1  2    3  4     5      6  7    8     9    10
0      1.0  0.0  0  1.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  1  0.0  5  2016  36203  0   20  64.2  2.0
2      1.0  0.0  0  1.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  1  0.0  3  2017  25952  0  145  67.3  2.0
4      1.0  0.0  0  1.0  2  2019   1998  2  145  49.6  1.0
...    ...  ... ..  ... ..   ...    ... ..  ...   ...  ...
10663  1.0  0.0  0  1.0  2  2020   4018  2  145  49.6  1.0
10664  1.0  0.0  0  1.0  2  2020   1978  2  150  49.6  1.0
10665  1.0  0.0  0  1.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  1  0.0  9  2017   8646  2  150  47.9  1.4
10667  1.0  0.0  0  1.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 11 columns]

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(x)
display (pd.DataFrame(x))


0    1  2    3  4     5      6  7    8     9    10
0      1.0  0.0  0  1.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  1  0.0  5  2016  36203  0   20  64.2  2.0
2      1.0  0.0  0  1.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  1  0.0  3  2017  25952  0  145  67.3  2.0
4      1.0  0.0  0  1.0  2  2019   1998  2  145  49.6  1.0
...    ...  ... ..  ... ..   ...    ... ..  ...   ...  ...
10663  1.0  0.0  0  1.0  2  2020   4018  2  145  49.6  1.0
10664  1.0  0.0  0  1.0  2  2020   1978  2  150  49.6  1.0
10665  1.0  0.0  0  1.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  1  0.0  9  2017   8646  2  150  47.9  1.4
10667  1.0  0.0  0  1.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 11 columns]

In [33]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size=0.2,random_state=0)


In [34]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(x_train,y_train)


C:\Users\PC\AppData\Local\Temp\ipykernel_13468\3890116324.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regression.fit(x_train,y_train)


RandomForestRegressor(random_state=0)

In [35]:
y_pred = regression.predict(x_test)
display (y_pred)


array([14274.37, 23493.8 , 27351.24, ..., 46322.12, 31282.2 ,  9942.21])

In [37]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(y_test,y_pred))


R2 Score  0.9528992929228634
Mean Absolute Error 1542.6081460056996


In [38]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)


LinearRegression()

In [40]:
y_pred = reg.predict(x_test)
display (y_pred)


array([[13052.36575395],
       [29340.03009442],
       [31908.12716369],
       ...,
       [42649.94612604],
       [31554.51438191],
       [ 7285.29079975]])

In [41]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[13052.36575395 14998.        ]
 [29340.03009442 21950.        ]
 [31908.12716369 28990.        ]
 ...
 [42649.94612604 45995.        ]
 [31554.51438191 30500.        ]
 [ 7285.29079975  8400.        ]]


In [42]:
print  ('R2 Score ', r2_score(y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(y_test,y_pred))
from sklearn.metrics import r2_score,mean_absolute_error


R2 Score  0.7916214142758088
Mean Absolute Error 3381.6733395891165


In [43]:
y_pred = reg.predict(x)
display (y_pred)


array([[14619.72352246],
       [20635.8666066 ],
       [13800.63070127],
       ...,
       [19396.77261227],
       [20998.77567375],
       [16680.79154354]])

In [44]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14619.723522  
1             2.0  20635.866607  
2             1.4  13800.630701  
3             2.0  19914.076834  
4             1.0  17339.679474  
...           ...           ...  
10663         1.0  19179.618582  
10664         1.0  19266.676532  
10665         1.0  19396.772612  
10666         1.4  20998.775674  
10667         1.4  16680.791544  

[10668 rows x 10 columns]

In [60]:
from sklearn.tree  import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit (x,y)
print (dt)

DecisionTreeRegressor()


In [61]:
y_pred = dt.predict(x)
print (y_pred)

[12500. 16500. 11000. ... 17199. 19499. 15999.]


In [62]:
y

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [70]:
accuracy = r2_score(y,y_pred)
print (accuracy)

0.9987853307224878


In [72]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize        0  
0             1.4  12500.0  
1             2.0  16500.0  
2             1.4  11000.0  
3             2.0  16800.0  
4             1.0  17300.0  
...           ...      ...  
10663         1.0  16999.0  
10664         1.0  16999.0  
10665         1.0  17199.0  
10666         1.4  19499.0  
10667         1.4  15999.0  

[10668 rows x 10 columns]